name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: check format
        run: deno fmt --check

      - name: lint all code
        run: deno lint

      - name: run tests
        run: deno task test

      - name: lint code documentation 
        run: deno doc --lint mod.ts

      - name: dummy publish
        run: deno publish --dry-run